(setq mu4e-headers-show-threads nil)

(setenv "XAPIAN_CJK_NGRAM" "1")
(setq message-send-mail-function 'smtpmail-send-it)
(setq message-default-charset 'utf-8)
(add-to-list 'mm-body-charset-encoding-alist '(utf-8 . base64))
(setq mu4e-get-mail-command "mbsync -a")
(setq mu4e-maildir-shortcuts '((:maildir "/titech/inbox" :key ?i)
                               (:maildir "/titech/drafts" :key ?d)))
(setq mu4e-context-policy 'pick-first)
(setq mu4e-compose-context-policy 'always-ask)
(setq mu4e-query-rewrite-function
      (lambda (query)
        (replace-regexp-in-string "\\([[:multibyte:]]\\)" "\\1 \\1" query)))
;;  (when (display-graphic-p) (setq mu4e-use-fancy-chars nil))
(with-eval-after-load "mm-decode"
  (add-to-list 'mm-discouraged-alternatives "text/html")
  (add-to-list 'mm-discouraged-alternatives "text/richtext"))
(setq mu4e-contexts nil)
(push (make-mu4e-context :name "titech"
                         :match-func (lambda (m)
                                       (when m (mu4e-message-contact-field-matches m :to "miyachi.f.aa@m.titech.ac.jp")))
                         :vars `((user-mail-address . ,"miyachi.f.aa@m.titech.ac.jp")
                                 (user-full-name . "宮地風汰")
                                 (smtpmail-smtp-server . "smtpv3.m.titech.ac.jp")
                                 (smtpmail-smtp-user . "miyachi.f.aa#kzw7")
                                 (smtpmail-smtp-service . 465)
                                 (smtpmail-auth-supported . (login))
                                 (smtpmail-stream-type . ssl)
                                 (auth-sources . ,(pcase system-type
                                                    ('gnu/linux '("~/.password-store/mail-titech.gpg"))
                                                    (_ '(macos-keychain-internet))))
                                 (mu4e-sent-folder . ,(concat "/titech/" "sent"))
                                 (mu4e-drafts-folder . ,(concat "/titech/" "drafts"))
                                 (mu4e-trash-folder . ,(concat "/titech/" "trash"))))
      mu4e-contexts)
;; (push (make-mu4e-context :name "gmail"
;;                          :match-func (lambda (m)
;;                                        (when m (mu4e-message-contact-field-matches m :to "miyachf@gmail.com")))
;;                          :vars `((user-mail-address . "miyachf@gmail.com")
;;                                  (user-full-name . "宮地風汰")
;;                                  (smtpmail-smtp-server . "smtp.gmail.com")
;;                                  (smtpmail-smtp-user . "miyachf@gmail.com")
;;                                  (smtpmail-smtp-service . 465)
;;                                  (smtpmail-auth-supported . (login))
;;                                  (smtpmail-stream-type . ssl)
;;                                  (mu4e-sent-messages-behavior . delete)
;;                                  (mu4e-sent-folder . ,(concat "/gmail/" "sent"))
;;                                  (mu4e-drafts-folder . ,(concat "/gmail/" "drafts"))
;;                                  (mu4e-trash-folder . ,(concat "/gmail/" "trash"))))
;;       mu4e-contexts))
